const pool = require("./server/db.js");

const MEDICINES = [
  // 1. Analgesic (Pain relief)
  { name: "Paracetamol 500mg", salt: "Paracetamol", category: "Analgesic", manufacturer: "GSK", price: 15, usage: "Fever and pain relief", req: false },
  { name: "Dolo 650", salt: "Paracetamol", category: "Analgesic", manufacturer: "Micro Labs", price: 30, usage: "High fever and pain", req: false },
  { name: "Calpol 500", salt: "Paracetamol", category: "Analgesic", manufacturer: "GSK", price: 18, usage: "Mild fever and headache", req: false },
  { name: "Combiflam", salt: "Ibuprofen & Paracetamol", category: "Analgesic", manufacturer: "Sanofi", price: 40, usage: "Body ache and inflammation", req: false },
  { name: "Crocin Advance", salt: "Paracetamol", category: "Analgesic", manufacturer: "GSK", price: 20, usage: "Fast pain relief", req: false },
  { name: "Ultracet", salt: "Tramadol & Paracetamol", category: "Analgesic", manufacturer: "Janssen", price: 180, usage: "Severe pain relief", req: true },
  { name: "Sumo", salt: "Nimesulide & Paracetamol", category: "Analgesic", manufacturer: "Alkem", price: 45, usage: "Acute pain relief", req: true },
  { name: "Zerodol P", salt: "Aceclofenac & Paracetamol", category: "Analgesic", manufacturer: "Ipsa", price: 60, usage: "Muscle and joint pain", req: true },
  { name: "Naproxen 250", salt: "Naproxen", category: "Analgesic", manufacturer: "Abbott", price: 35, usage: "Anti-inflammatory pain relief", req: true },
  { name: "Meftal Spas", salt: "Mefenamic Acid & Dicyclomine", category: "Analgesic", manufacturer: "Blue Cross", price: 50, usage: "Menstrual pain relief", req: false },
  { name: "Dart", salt: "Paracetamol & Caffeine", category: "Analgesic", manufacturer: "Bayer", price: 25, usage: "Headache relief", req: false },
  { name: "Saridon", salt: "Paracetamol & Propyphenazone", category: "Analgesic", manufacturer: "Piramal", price: 12, usage: "Quick headache relief", req: false },
  { name: "Anacin", salt: "Aspirin & Caffeine", category: "Analgesic", manufacturer: "Pfizer", price: 15, usage: "General pain and cold", req: false },
  { name: "Imol", salt: "Ibuprofen & Paracetamol", category: "Analgesic", manufacturer: "Zydus", price: 30, usage: "Pain and swelling", req: false },
  { name: "Voveran SR 75", salt: "Diclofenac", category: "Analgesic", manufacturer: "Novartis", price: 90, usage: "Long acting pain relief", req: true },

  // 2. Antibiotic
  { name: "Azithromycin 500", salt: "Azithromycin", category: "Antibiotic", manufacturer: "Cipla", price: 120, usage: "Bacterial infection treatment", req: true },
  { name: "Amoxicillin 500mg", salt: "Amoxicillin", category: "Antibiotic", manufacturer: "Ranbaxy", price: 85, usage: "Treats throat and ear infections", req: true },
  { name: "Augmentin 625", salt: "Amoxicillin & Clavulanate", category: "Antibiotic", manufacturer: "GSK", price: 210, usage: "Strong bacterial treatment", req: true },
  { name: "Cefixime 200", salt: "Cefixime", category: "Antibiotic", manufacturer: "Lupin", price: 110, usage: "Treats typhoid and UTI", req: true },
  { name: "Doxycycline 100", salt: "Doxycycline", category: "Antibiotic", manufacturer: "USV", price: 45, usage: "Acne and bacterial infections", req: true },
  { name: "Oflox 200", salt: "Ofloxacin", category: "Antibiotic", manufacturer: "Cipla", price: 65, usage: "Gastrointestinal infections", req: true },
  { name: "Norflox 400", salt: "Norfloxacin", category: "Antibiotic", manufacturer: "Cipla", price: 55, usage: "Urinary tract infections", req: true },
  { name: "Cipro 500", salt: "Ciprofloxacin", category: "Antibiotic", manufacturer: "Bayer", price: 40, usage: "Broad spectrum antibiotic", req: true },
  { name: "Azithral 500", salt: "Azithromycin", category: "Antibiotic", manufacturer: "Alembic", price: 115, usage: "Chest infection treatment", req: true },
  { name: "Zady 500", salt: "Azithromycin", category: "Antibiotic", manufacturer: "Mankind", price: 105, usage: "Respiratory tract infections", req: true },
  { name: "Taxim O 200", salt: "Cefixime", category: "Antibiotic", manufacturer: "Alkem", price: 100, usage: "Infectious diseases", req: true },
  { name: "Moxikind CV 625", salt: "Amoxicillin & Clavulanate", category: "Antibiotic", manufacturer: "Mankind", price: 190, usage: "Severe infections", req: true },
  { name: "Roxid 150", salt: "Roxithromycin", category: "Antibiotic", manufacturer: "Alembic", price: 80, usage: "Ear and nose infections", req: true },
  { name: "Klavam 625", salt: "Amoxicillin & Clavulanate", category: "Antibiotic", manufacturer: "Alkem", price: 205, usage: "Mixed bacterial infections", req: true },
  { name: "Metrogyl 400", salt: "Metronidazole", category: "Antibiotic", manufacturer: "J.B. Chemicals", price: 25, usage: "Stomach infection treatment", req: true },

  // 3. Antidiabetic
  { name: "Metformin 500", salt: "Metformin", category: "Antidiabetic", manufacturer: "Cipla", price: 35, usage: "Controls blood sugar", req: true },
  { name: "Glycomet GP 1", salt: "Metformin & Glimepiride", category: "Antidiabetic", manufacturer: "USV", price: 85, usage: "Type 2 diabetes management", req: true },
  { name: "Glimepiride 2mg", salt: "Glimepiride", category: "Antidiabetic", manufacturer: "Ranbaxy", price: 45, usage: "Insulin production booster", req: true },
  { name: "Januvia 100", salt: "Sitagliptin", category: "Antidiabetic", manufacturer: "MSD", price: 450, usage: "Advanced blood sugar control", req: true },
  { name: "Insulin Glargine", salt: "Insulin", category: "Antidiabetic", manufacturer: "Sanofi", price: 650, usage: "Long acting insulin", req: true },
  { name: "Galvus 50", salt: "Vildagliptin", category: "Antidiabetic", manufacturer: "Novartis", price: 320, usage: "Blood glucose control", req: true },
  { name: "Jalra 50", salt: "Vildagliptin", category: "Antidiabetic", manufacturer: "USV", price: 310, usage: "Controls post-meal sugar", req: true },
  { name: "Forxiga 10", salt: "Dapagliflozin", category: "Antidiabetic", manufacturer: "AstraZeneca", price: 580, usage: "Sugar removal via kidneys", req: true },
  { name: "Jardiance 10", salt: "Empagliflozin", category: "Antidiabetic", manufacturer: "Boehringer Ingelheim", price: 560, usage: "Heart protection in diabetes", req: true },
  { name: "Glynase 5", salt: "Glipizide", category: "Antidiabetic", manufacturer: "Pfizer", price: 40, usage: "Fast acting sugar control", req: true },
  { name: "Pioglit 15", salt: "Pioglitazone", category: "Antidiabetic", manufacturer: "Sun Pharma", price: 75, usage: "Insulin sensitivity booster", req: true },
  { name: "Teneligliptin 20", salt: "Teneligliptin", category: "Antidiabetic", manufacturer: "Glenmark", price: 120, usage: "DDP-4 inhibitor for sugar", req: true },
  { name: "Voglibose 0.3", salt: "Voglibose", category: "Antidiabetic", manufacturer: "Sun Pharma", price: 90, usage: "Post-meal sugar spike control", req: true },
  { name: "Amaryl 1mg", salt: "Glimepiride", category: "Antidiabetic", manufacturer: "Sanofi", price: 60, usage: "Daily diabetes tablet", req: true },
  { name: "Glucobay 50", salt: "Acarbose", category: "Antidiabetic", manufacturer: "Bayer", price: 110, usage: "Carbohydrate digestion delayer", req: true },

  // 4. Antacid
  { name: "Omez 20", salt: "Omeprazole", category: "Antacid", manufacturer: "Dr. Reddy's", price: 50, usage: "Reduces stomach acid", req: false },
  { name: "Pantop 40", salt: "Pantoprazole", category: "Antacid", manufacturer: "Aristo", price: 75, usage: "Acidity and reflux", req: false },
  { name: "Pan D", salt: "Pantoprazole & Domperidone", category: "Antacid", manufacturer: "Alkem", price: 110, usage: "Acidity with nausea", req: false },
  { name: "Gelusil Syrup", salt: "Aluminum Hydroxide & Magnesium", category: "Antacid", manufacturer: "Pfizer", price: 120, usage: "Quick heartburn relief", req: false },
  { name: "Digene Tablet", salt: "Magnesium Hydroxide", category: "Antacid", manufacturer: "Abbott", price: 18, usage: "Indigestion and gas", req: false },
  { name: "Sompraz 40", salt: "Esomeprazole", category: "Antacid", manufacturer: "Sun Pharma", price: 130, usage: "Severe acid management", req: true },
  { name: "Rantac 150", salt: "Ranitidine", category: "Antacid", manufacturer: "J.B. Chemicals", price: 30, usage: "General acidity", req: false },
  { name: "Aciloc 150", salt: "Ranitidine", category: "Antacid", manufacturer: "Cadila", price: 28, usage: "Stomach burning relief", req: false },
  { name: "Rabium 20", salt: "Rabeprazole", category: "Antacid", manufacturer: "Intas", price: 85, usage: "Fast acting acid blocker", req: true },
  { name: "Pantocid 40", salt: "Pantoprazole", category: "Antacid", manufacturer: "Sun Pharma", price: 95, usage: "Chronic acidity treatment", req: true },
  { name: "Omez D", salt: "Omeprazole & Domperidone", category: "Antacid", manufacturer: "Dr. Reddy's", price: 105, usage: "Gastritis and bloating", req: true },
  { name: "Zinetac 150", salt: "Ranitidine", category: "Antacid", manufacturer: "GSK", price: 35, usage: "Relieves indigestion", req: false },
  { name: "Mucaine Gel", salt: "Oxetacaine & Aluminum", category: "Antacid", manufacturer: "Pfizer", price: 160, usage: "Painful acidity relief", req: false },
  { name: "Pepfiz", salt: "Papain & Simethicone", category: "Antacid", manufacturer: "Ranbaxy", price: 15, usage: "Effervescent digestive aid", req: false },
  { name: "Eno Powder", salt: "Sodium Bicarbonate", category: "Antacid", manufacturer: "GSK", price: 10, usage: "6-second acidity relief", req: false },

  // 5. NSAID
  { name: "Brufen 400", salt: "Ibuprofen", category: "NSAID", manufacturer: "Abbott", price: 25, usage: "Inflammation and pain", req: false },
  { name: "Naprosyn 500", salt: "Naproxen", category: "NSAID", manufacturer: "RPG Life", price: 45, usage: "Arthritis pain relief", req: true },
  { name: "Zerodol SP", salt: "Aceclofenac & Serratiopeptidase", category: "NSAID", manufacturer: "Ipsa", price: 120, usage: "Pain with swelling", req: true },
  { name: "Ketorol DT", salt: "Ketorolac", category: "NSAID", manufacturer: "Dr. Reddy's", price: 80, usage: "Dental pain relief", req: true },
  { name: "Etoshine 90", salt: "Etoricoxib", category: "NSAID", manufacturer: "Sun Pharma", price: 150, usage: "Joint pain management", req: true },
  { name: "Voveran 50", salt: "Diclofenac", category: "NSAID", manufacturer: "Novartis", price: 45, usage: "Back and muscle pain", req: true },
  { name: "Diclomol", salt: "Diclofenac & Paracetamol", category: "NSAID", manufacturer: "Win-Medicare", price: 35, usage: "Acute body pain", req: true },
  { name: "Piroxicam 20", salt: "Piroxicam", category: "NSAID", manufacturer: "Pfizer", price: 55, usage: "Severe joint inflammation", req: true },
  { name: "Lornoxicam 8", salt: "Lornoxicam", category: "NSAID", manufacturer: "Glenmark", price: 95, usage: "Osteoarthritis relief", req: true },
  { name: "Nimulid", salt: "Nimesulide", category: "NSAID", manufacturer: "Panacea Biotec", price: 40, usage: "Rapid fever and pain control", req: true },
  { name: "Dolonex DT", salt: "Piroxicam", category: "NSAID", manufacturer: "Pfizer", price: 110, usage: "Fast dissolving painkiller", req: true },
  { name: "Indocap 25", salt: "Indomethacin", category: "NSAID", manufacturer: "Jagsonpal", price: 65, usage: "Gout pain treatment", req: true },
  { name: "Artisid", salt: "Indomethacin", category: "NSAID", manufacturer: "Sun Pharma", price: 70, usage: "Spondylitis management", req: true },
  { name: "Dynapar 50", salt: "Diclofenac", category: "NSAID", manufacturer: "Troikaa", price: 50, usage: "Injected or oral pain relief", req: true },
  { name: "Flexon", salt: "Ibuprofen & Paracetamol", category: "NSAID", manufacturer: "Aristo", price: 32, usage: "Sprain and strain pain", req: false },

  // 6. Antihistamine
  { name: "Avil 25", salt: "Pheniramine", category: "Antihistamine", manufacturer: "Sanofi", price: 12, usage: "Allergy and runny nose", req: false },
  { name: "Cetirizine 10", salt: "Cetirizine", category: "Antihistamine", manufacturer: "Cipla", price: 20, usage: "General allergy relief", req: false },
  { name: "Zyrtec 10", salt: "Cetirizine", category: "Antihistamine", manufacturer: "J&J", price: 35, usage: "Long acting allergy relief", req: false },
  { name: "Allegra 120", salt: "Fexofenadine", category: "Antihistamine", manufacturer: "Sanofi", price: 180, usage: "Non-drowsy allergy relief", req: false },
  { name: "Montair LC", salt: "Montelukast & Levocetirizine", category: "Antihistamine", manufacturer: "Cipla", price: 220, usage: "Allergy and asthma", req: true },
  { name: "Levocet 5", salt: "Levocetirizine", category: "Antihistamine", manufacturer: "Cipla", price: 45, usage: "Itching and sneezing", req: false },
  { name: "Atarax 25", salt: "Hydroxyzine", category: "Antihistamine", manufacturer: "Dr. Reddy's", price: 90, usage: "Skin itching and anxiety", req: true },
  { name: "Bilaxten 20", salt: "Bilastine", category: "Antihistamine", manufacturer: "Menarini", price: 150, usage: "Chronic hives relief", req: true },
  { name: "Telfast 120", salt: "Fexofenadine", category: "Antihistamine", manufacturer: "Sanofi", price: 190, usage: "Seasonal allergy relief", req: false },
  { name: "Loratadine 10", salt: "Loratadine", category: "Antihistamine", manufacturer: "Sun Pharma", price: 30, usage: "Daily allergy tablet", req: false },
  { name: "Claritin", salt: "Loratadine", category: "Antihistamine", manufacturer: "Bayer", price: 40, usage: "Non-drowsy sneezing relief", req: false },
  { name: "Alerid", salt: "Cetirizine", category: "Antihistamine", manufacturer: "Cipla", price: 22, usage: "Cheap allergy control", req: false },
  { name: "Okacet", salt: "Cetirizine", category: "Antihistamine", manufacturer: "Cipla", price: 18, usage: "Standard allergy pill", req: false },
  { name: "Cetzine", salt: "Cetirizine", category: "Antihistamine", manufacturer: "GSK", price: 25, usage: "Reliable allergy relief", req: false },
  { name: "Histafree 120", salt: "Fexofenadine", category: "Antihistamine", manufacturer: "Mankind", price: 140, usage: "Modern antihistamine", req: false },

  // 7. Antihypertensive
  { name: "Telma 40", salt: "Telmisartan", category: "Antihypertensive", manufacturer: "Glenmark", price: 110, usage: "High blood pressure", req: true },
  { name: "Amlokind 5", salt: "Amlodipine", category: "Antihypertensive", manufacturer: "Mankind", price: 35, usage: "Blood pressure control", req: true },
  { name: "Envas 5", salt: "Enalapril", category: "Antihypertensive", manufacturer: "Cipla", price: 40, usage: "Heart failure and BP", req: true },
  { name: "Losar 50", salt: "Losartan", category: "Antihypertensive", manufacturer: "Unichem", price: 95, usage: "Renal protection in BP", req: true },
  { name: "Metosartan 50", salt: "Metoprolol & Telmisartan", category: "Antihypertensive", manufacturer: "Sun Pharma", price: 160, usage: "Combined BP management", req: true },
  { name: "Cilacar 10", salt: "Cilnidipine", category: "Antihypertensive", manufacturer: "J.B. Chemicals", price: 130, usage: "BP with kidney safety", req: true },
  { name: "Revelol XL 25", salt: "Metoprolol", category: "Antihypertensive", manufacturer: "Ipsa", price: 80, usage: "Beta blocker for BP", req: true },
  { name: "Stamp 5", salt: "Amlodipine", category: "Antihypertensive", manufacturer: "Zydus", price: 38, usage: "Chronic hypertension", req: true },
  { name: "Ramipril 5", salt: "Ramipril", category: "Antihypertensive", manufacturer: "Lupin", price: 55, usage: "ACE inhibitor for heart", req: true },
  { name: "Concor 5", salt: "Bisoprolol", category: "Antihypertensive", manufacturer: "Merck", price: 140, usage: "BP and heart rate", req: true },
  { name: "Nebistar 5", salt: "Nebivolol", category: "Antihypertensive", manufacturer: "Lupin", price: 120, usage: "Vasodilating beta blocker", req: true },
  { name: "Telsar 40", salt: "Telmisartan", category: "Antihypertensive", manufacturer: "Unichem", price: 105, usage: "Vascular health in BP", req: true },
  { name: "Azulix 2", salt: "Glimepiride", category: "Antihypertensive", manufacturer: "Torrent", price: 85, usage: "Often prescribed with BP", req: true },
  { name: "Olmesar 20", salt: "Olmesartan", category: "Antihypertensive", manufacturer: "Macleods", price: 150, usage: "Strong BP reduction", req: true },
  { name: "Tazloc 40", salt: "Telmisartan", category: "Antihypertensive", manufacturer: "USV", price: 115, usage: "Standard hypertension pill", req: true },

  // 8. Asthma
  { name: "Asthalin Inhaler", salt: "Salbutamol", category: "Asthma", manufacturer: "Cipla", price: 150, usage: "Relief from wheezing", req: true },
  { name: "Foracort 200", salt: "Formoterol & Budesonide", category: "Asthma", manufacturer: "Cipla", price: 450, usage: "Asthma maintenance", req: true },
  { name: "Duolin Inhaler", salt: "Levosalbutamol & Ipratropium", category: "Asthma", manufacturer: "Cipla", price: 420, usage: "Chronic COPD relief", req: true },
  { name: "Budecort 200", salt: "Budesonide", category: "Asthma", manufacturer: "Cipla", price: 380, usage: "Steroid inhaler for asthma", req: true },
  { name: "Deriphyllin", salt: "Theophylline & Etofylline", category: "Asthma", manufacturer: "Zydus", price: 20, usage: "Easy breathing tablet", req: true },
  { name: "Seroflo 250", salt: "Salmeterol & Fluticasone", category: "Asthma", manufacturer: "Cipla", price: 650, usage: "Long term asthma control", req: true },
  { name: "Tiova Inhaler", salt: "Tiotropium", category: "Asthma", manufacturer: "Cipla", price: 580, usage: "Once daily COPD relief", req: true },
  { name: "Levolin Syrup", salt: "Levosalbutamol", category: "Asthma", manufacturer: "Cipla", price: 65, usage: "Pediatric asthma relief", req: true },
  { name: "Aerocort Inhaler", salt: "Beclomethasone & Salbutamol", category: "Asthma", manufacturer: "Cipla", price: 280, usage: "Combined asthma therapy", req: true },
  { name: "Ventorlin", salt: "Salbutamol", category: "Asthma", manufacturer: "GSK", price: 35, usage: "Standard bronchodilator", req: true },
  { name: "Montair 10", salt: "Montelukast", category: "Asthma", manufacturer: "Cipla", price: 190, usage: "Leukotriene blocker for asthma", req: true },
  { name: "Singulair 10", salt: "Montelukast", category: "Asthma", manufacturer: "MSD", price: 350, usage: "Premium asthma prevention", req: true },
  { name: "Doxofylline 400", salt: "Doxofylline", category: "Asthma", manufacturer: "Sun Pharma", price: 130, usage: "Next gen asthma tablet", req: true },
  { name: "Bambudil 10", salt: "Bambuterol", category: "Asthma", manufacturer: "AstraZeneca", price: 110, usage: "Long acting wheeze relief", req: true },
  { name: "Theo-Asthalin", salt: "Theophylline & Salbutamol", category: "Asthma", manufacturer: "Cipla", price: 30, usage: "Combined lung opener", req: true },

  // 9. Steroid
  { name: "Wysolone 10", salt: "Prednisolone", category: "Steroid", manufacturer: "Pfizer", price: 15, usage: "Severe inflammation", req: true },
  { name: "Dexona", salt: "Dexamethasone", category: "Steroid", manufacturer: "Zydus", price: 10, usage: "Anti-inflammatory steroid", req: true },
  { name: "Omnacortil 5", salt: "Prednisolone", category: "Steroid", manufacturer: "Macleods", price: 12, usage: "Pediatric steroid dosage", req: true },
  { name: "Betnesol", salt: "Betamethasone", category: "Steroid", manufacturer: "GSK", price: 8, usage: "Quick allergy steroid", req: true },
  { name: "Medrol 4mg", salt: "Methylprednisolone", category: "Steroid", manufacturer: "Pfizer", price: 65, usage: "Potent anti-inflammatory", req: true },
  { name: "Defcort 6", salt: "Deflazacort", category: "Steroid", manufacturer: "Macleods", price: 140, usage: "Newer bone-safe steroid", req: true },
  { name: "Decadron", salt: "Dexamethasone", category: "Steroid", manufacturer: "Wockhardt", price: 15, usage: "Hospital grade steroid", req: true },
  { name: "Kenacort 40", salt: "Triamcinolone", category: "Steroid", manufacturer: "Abbott", price: 180, usage: "Injectable joint steroid", req: true },
  { name: "Caldicort", salt: "Deflazacort", category: "Steroid", manufacturer: "Zydus", price: 130, usage: "General steroid therapy", req: true },
  { name: "Solu-Medrol", salt: "Methylprednisolone", category: "Steroid", manufacturer: "Pfizer", price: 550, usage: "Emergency IV steroid", req: true },
  { name: "Predone 10", salt: "Prednisolone", category: "Steroid", manufacturer: "Cipla", price: 18, usage: "Allergic reaction control", req: true },
  { name: "Cortil 10", salt: "Hydrocortisone", category: "Steroid", manufacturer: "Sun Pharma", price: 90, usage: "Adrenal hormone replacement", req: true },
  { name: "Hydrocort Injection", salt: "Hydrocortisone", category: "Steroid", manufacturer: "Abbott", price: 45, usage: "Acute shock treatment", req: true },
  { name: "Zcort 6", salt: "Deflazacort", category: "Steroid", manufacturer: "Zydus", price: 125, usage: "Muscle inflammation relief", req: true },
  { name: "Dermocort Cream", salt: "Hydrocortisone", category: "Steroid", manufacturer: "Glenmark", price: 70, usage: "Topical skin steroid", req: false },

  // 10. Antiepileptic
  { name: "Levipil 500", salt: "Levetiracetam", category: "Antiepileptic", manufacturer: "Sun Pharma", price: 130, usage: "Seizure prevention", req: true },
  { name: "Eptoin 100", salt: "Phenytoin", category: "Antiepileptic", manufacturer: "Abbott", price: 45, usage: "Epilepsy control", req: true },
  { name: "Encorate Chrono 300", salt: "Sodium Valproate", category: "Antiepileptic", manufacturer: "Sun Pharma", price: 110, usage: "Broad spectrum seizure control", req: true },
  { name: "Gardenal 30", salt: "Phenobarbital", category: "Antiepileptic", manufacturer: "Abbott", price: 25, usage: "Long term seizure control", req: true },
  { name: "Valparin Alkalets 200", salt: "Sodium Valproate", category: "Antiepileptic", manufacturer: "Sanofi", price: 85, usage: "Standard epilepsy tablet", req: true },
  { name: "Tegritol 200", salt: "Carbamazepine", category: "Antiepileptic", manufacturer: "Novartis", price: 60, usage: "Nerve pain and seizures", req: true },
  { name: "Mazetol 200", salt: "Carbamazepine", category: "Antiepileptic", manufacturer: "Abbott", price: 55, usage: "Facial nerve pain relief", req: true },
  { name: "Gabapin 300", salt: "Gabapentin", category: "Antiepileptic", manufacturer: "Intas", price: 180, usage: "Neuropathic pain control", req: true },
  { name: "Pregalin 75", salt: "Pregabalin", category: "Antiepileptic", manufacturer: "Torrent", price: 150, usage: "Nerve damage pain relief", req: true },
  { name: "Lyrica 75", salt: "Pregabalin", category: "Antiepileptic", manufacturer: "Pfizer", price: 450, usage: "Premium nerve pain relief", req: true },
  { name: "Keppra 500", salt: "Levetiracetam", category: "Antiepileptic", manufacturer: "UCB India", price: 380, usage: "Modern seizure therapy", req: true },
  { name: "Lacomet 100", salt: "Lacosamide", category: "Antiepileptic", manufacturer: "Sun Pharma", price: 220, usage: "Newer focal seizure drug", req: true },
  { name: "Oxmazetol 300", salt: "Oxcarbazepine", category: "Antiepileptic", manufacturer: "Sun Pharma", price: 160, usage: "Stable epilepsy control", req: true },
  { name: "Zonisep 50", salt: "Zonisamide", category: "Antiepileptic", manufacturer: "Sun Pharma", price: 140, usage: "Adjunctive seizure therapy", req: true },
  { name: "Frisium 10", salt: "Clobazam", category: "Antiepileptic", manufacturer: "Sanofi", price: 110, usage: "Severe seizure supplement", req: true },

  // 11. Liver Care
  { name: "Liv 52", salt: "Herbal Extract", category: "Liver Care", manufacturer: "Himalaya", price: 150, usage: "Improves liver function", req: false },
  { name: "Udiliv 300", salt: "Ursodeoxycholic Acid", category: "Liver Care", manufacturer: "Abbott", price: 550, usage: "Dissolves gallstones", req: true },
  { name: "Hepamerz", salt: "L-Ornithine L-Aspartate", category: "Liver Care", manufacturer: "Win-Medicare", price: 420, usage: "Liver detoxification", req: true },
  { name: "Silybon 140", salt: "Silymarin", category: "Liver Care", manufacturer: "Micro Labs", price: 180, usage: "Protects liver cells", req: false },
  { name: "Ursocol 300", salt: "Ursodeoxycholic Acid", category: "Liver Care", manufacturer: "Sun Pharma", price: 540, usage: "Liver bile flow improver", req: true },
  { name: "Heptral 400", salt: "Ademetionine", category: "Liver Care", manufacturer: "Abbott", price: 950, usage: "Advanced liver regeneration", req: true },
  { name: "Liveril", salt: "Multivitamin & Silymarin", category: "Liver Care", manufacturer: "Meyer Vitabiotics", price: 320, usage: "Comprehensive liver health", req: false },
  { name: "Amlycure DS", salt: "Ayurvedic", category: "Liver Care", manufacturer: "Aimil", price: 180, usage: "Liver enzyme correction", req: false },
  { name: "Livomyn", salt: "Herbal", category: "Liver Care", manufacturer: "Charak", price: 110, usage: "Liver tonic and protection", req: false },
  { name: "Stimuliv", salt: "Herbal", category: "Liver Care", manufacturer: "Franco-Indian", price: 90, usage: "Appetite and liver booster", req: false },
  { name: "Sorbiline", salt: "Sorbitol & Tricholine", category: "Liver Care", manufacturer: "Franco-Indian", price: 130, usage: "Digestive and liver aid", req: false },
  { name: "Hepa-Merz Infusion", salt: "L-Ornithine", category: "Liver Care", manufacturer: "Win-Medicare", price: 1200, usage: "Severe liver failure IV", req: true },
  { name: "Cirrosam 400", salt: "Ademetionine", category: "Liver Care", manufacturer: "Lupin", price: 880, usage: "Chronic liver support", req: true },
  { name: "Liv 52 HB", salt: "Herbal Extract", category: "Liver Care", manufacturer: "Himalaya", price: 250, usage: "Specialized hepatitis support", req: false },
  { name: "Silybon Suspension", salt: "Silymarin", category: "Liver Care", manufacturer: "Micro Labs", price: 150, usage: "Child liver protection", req: false },

  // 12. Kidney Care
  { name: "Cystone", salt: "Herbal Extract", category: "Kidney Care", manufacturer: "Himalaya", price: 165, usage: "Prevents kidney stones", req: false },
  { name: "Nephrotrans", salt: "Sodium Bicarbonate", category: "Kidney Care", manufacturer: "Alkem", price: 280, usage: "Kidney acid control", req: true },
  { name: "Renolog", salt: "Alpha Ketoanalogue", category: "Kidney Care", manufacturer: "Alniche", price: 850, usage: "Protects kidney function", req: true },
  { name: "Ketoanalogues", salt: "Ketoanalogues", category: "Kidney Care", manufacturer: "Fresenius Kabi", price: 1200, usage: "Advanced kidney therapy", req: true },
  { name: "Feburic 40", salt: "Febuxostat", category: "Kidney Care", manufacturer: "Sun Pharma", price: 140, usage: "Lowers uric acid", req: true },
  { name: "Zyloric 100", salt: "Allopurinol", category: "Kidney Care", manufacturer: "GSK", price: 35, usage: "Gout and stone prevention", req: true },
  { name: "Stone-1 Syrup", salt: "Ayurvedic", category: "Kidney Care", manufacturer: "Zydus", price: 150, usage: "Dissolves small stones", req: false },
  { name: "Nefrosave", salt: "Taurine & Acetylcysteine", category: "Kidney Care", manufacturer: "Fourrts", price: 320, usage: "Preventing kidney damage", req: true },
  { name: "Nephrosafe", salt: "Taurine", category: "Kidney Care", manufacturer: "Alniche", price: 310, usage: "Supportive kidney care", req: true },
  { name: "Cital Syrup", salt: "Disodium Hydrogen Citrate", category: "Kidney Care", manufacturer: "Indoco", price: 95, usage: "Urine alkalizer for stones", req: false },
  { name: "Alkasol Syrup", salt: "Disodium Hydrogen Citrate", category: "Kidney Care", manufacturer: "Stadmed", price: 100, usage: "Burning urination relief", req: false },
  { name: "Urisol", salt: "Flavoxate", category: "Kidney Care", manufacturer: "Cipla", price: 180, usage: "Urinary tract pain relief", req: true },
  { name: "Urimax 0.4", salt: "Tamsulosin", category: "Kidney Care", manufacturer: "Cipla", price: 210, usage: "Easier urination for men", req: true },
  { name: "Dutasteride 0.5", salt: "Dutasteride", category: "Kidney Care", manufacturer: "Sun Pharma", price: 250, usage: "Prostate shrinkage", req: true },
  { name: "Veltam 0.4", salt: "Tamsulosin", category: "Kidney Care", manufacturer: "Intas", price: 195, usage: "Standard prostate care", req: true },

  // 13. Laxative
  { name: "Isabgol", salt: "Psyllium Husk", category: "Laxative", manufacturer: "Dabur", price: 220, usage: "Natural constipation relief", req: false },
  { name: "Cremaffin", salt: "Liquid Paraffin", category: "Laxative", manufacturer: "Abbott", price: 240, usage: "Gentle stool softener", req: false },
  { name: "Dulcolax", salt: "Bisacodyl", category: "Laxative", manufacturer: "Sanofi", price: 12, usage: "Overnight constipation relief", req: false },
  { name: "Looz Syrup", salt: "Lactulose", category: "Laxative", manufacturer: "Intas", price: 210, usage: "Chronic constipation relief", req: false },
  { name: "Duphalac", salt: "Lactulose", category: "Laxative", manufacturer: "Abbott", price: 250, usage: "Safe long-term laxative", req: false },
  { name: "Softovac Powder", salt: "Ayurvedic", category: "Laxative", manufacturer: "Lupin", price: 180, usage: "Herbal bowel regulator", req: false },
  { name: "Kayachurn", salt: "Ayurvedic", category: "Laxative", manufacturer: "Sheth Bros", price: 90, usage: "Traditional constipation aid", req: false },
  { name: "Pet Saffa", salt: "Ayurvedic", category: "Laxative", manufacturer: "Divisa", price: 95, usage: "Fast acting herbal laxative", req: false },
  { name: "Natrolax", salt: "Lactulose", category: "Laxative", manufacturer: "Sun Pharma", price: 190, usage: "Reliable stool softener", req: false },
  { name: "Lubrijoint", salt: "Glucosamine", category: "Laxative", manufacturer: "Wallace", price: 350, usage: "Joint lubrication (Misc)", req: false },
  { name: "Pegmove", salt: "Polyethylene Glycol", category: "Laxative", manufacturer: "Alkem", price: 380, usage: "Medical bowel prep", req: true },
  { name: "Cremaffin Plus", salt: "Liquid Paraffin & Picosulfate", category: "Laxative", manufacturer: "Abbott", price: 280, usage: "Strong constipation relief", req: false },
  { name: "Relub", salt: "Lactulose", category: "Laxative", manufacturer: "Lupin", price: 200, usage: "Stool softening syrup", req: false },
  { name: "Evict Syrup", salt: "Lactulose", category: "Laxative", manufacturer: "Albert David", price: 185, usage: "Pediatric safe laxative", req: false },
  { name: "Nulax", salt: "Senna", category: "Laxative", manufacturer: "Nu-Lax", price: 150, usage: "Fruit-based laxative", req: false },

  // 14. Cough Syrup
  { name: "Ascoril LS", salt: "Ambroxol & Levosalbutamol", category: "Cough Syrup", manufacturer: "Glenmark", price: 115, usage: "Wet cough relief", req: false },
  { name: "Benadryl DR", salt: "Dextromethorphan", category: "Cough Syrup", manufacturer: "J&J", price: 140, usage: "Dry cough relief", req: false },
  { name: "Grilinctus", salt: "Dextromethorphan & CPM", category: "Cough Syrup", manufacturer: "Franco-Indian", price: 130, usage: "General cough and cold", req: false },
  { name: "Alex Syrup", salt: "Dextromethorphan", category: "Cough Syrup", manufacturer: "Glenmark", price: 125, usage: "Non-drowsy dry cough", req: false },
  { name: "Phensedyl New", salt: "Codeine & CPM", category: "Cough Syrup", manufacturer: "Abbott", price: 160, usage: "Severe cough relief", req: true },
  { name: "Corex DX", salt: "Dextromethorphan", category: "Cough Syrup", manufacturer: "Pfizer", price: 145, usage: "Reliable dry cough syrup", req: false },
  { name: "Chericof", salt: "Dextromethorphan & Phenylephrine", category: "Cough Syrup", manufacturer: "Sun Pharma", price: 110, usage: "Cough with congestion", req: false },
  { name: "Zedex", salt: "Bromhexine & Dextromethorphan", category: "Cough Syrup", manufacturer: "Wockhardt", price: 120, usage: "Mucus breaking cough syrup", req: false },
  { name: "Viscodyne LS", salt: "Ambroxol", category: "Cough Syrup", manufacturer: "Wockhardt", price: 100, usage: "Productive cough aid", req: false },
  { name: "Torex Syrup", salt: "Diphenhydramine", category: "Cough Syrup", manufacturer: "Torque", price: 90, usage: "Allergic cough relief", req: false },
  { name: "Solvin Cough", salt: "Dextromethorphan", category: "Cough Syrup", manufacturer: "Ipsa", price: 115, usage: "Cold and cough syrup", req: false },
  { name: "Bro-Zedex", salt: "Terbutaline & Bromhexine", category: "Cough Syrup", manufacturer: "Wockhardt", price: 135, usage: "Asthmatic cough relief", req: true },
  { name: "Ambrodil", salt: "Ambroxol", category: "Cough Syrup", manufacturer: "Aristo", price: 85, usage: "Mucus thinner", req: false },
  { name: "Koflet", salt: "Herbal", category: "Cough Syrup", manufacturer: "Himalaya", price: 110, usage: "Ayurvedic cough relief", req: false },
  { name: "Honitus", salt: "Herbal", category: "Cough Syrup", manufacturer: "Dabur", price: 95, usage: "Honey-based cough aid", req: false },

  // 15. Hormone
  { name: "Thyronorm 50", salt: "Thyroxine", category: "Hormone", manufacturer: "Abbott", price: 160, usage: "Hypothyroidism treatment", req: true },
  { name: "Eltroxin 50", salt: "Thyroxine", category: "Hormone", manufacturer: "GSK", price: 155, usage: "Thyroid hormone replacement", req: true },
  { name: "Dydroboon", salt: "Dydrogesterone", category: "Hormone", manufacturer: "Mankind", price: 650, usage: "Pregnancy support", req: true },
  { name: "Duphaston", salt: "Dydrogesterone", category: "Hormone", manufacturer: "Abbott", price: 850, usage: "Progesterone hormone", req: true },
  { name: "Susten 200", salt: "Progesterone", category: "Hormone", manufacturer: "Sun Pharma", price: 420, usage: "Hormonal imbalance aid", req: true },
  { name: "Progynova 2", salt: "Estradiol", category: "Hormone", manufacturer: "Bayer", price: 380, usage: "Estrogen replacement", req: true },
  { name: "Ovral L", salt: "Levonorgestrel & Ethinyl Estradiol", category: "Hormone", manufacturer: "Pfizer", price: 210, usage: "Contraception and cycles", req: true },
  { name: "Unwanted 72", salt: "Levonorgestrel", category: "Hormone", manufacturer: "Mankind", price: 100, usage: "Emergency contraception", req: false },
  { name: "i-Pill", salt: "Levonorgestrel", category: "Hormone", manufacturer: "Piramal", price: 110, usage: "Emergency morning after pill", req: false },
  { name: "Meprate 10", salt: "Medroxyprogesterone", category: "Hormone", manufacturer: "Serum Institute", price: 90, usage: "Period regulation", req: true },
  { name: "Premarin", salt: "Conjugated Estrogens", category: "Hormone", manufacturer: "Pfizer", price: 750, usage: "Menopause symptoms", req: true },
  { name: "Novelon", salt: "Desogestrel", category: "Hormone", manufacturer: "Organon", price: 250, usage: "Modern birth control", req: true },
  { name: "Danogen 200", salt: "Danazol", category: "Hormone", manufacturer: "Cipla", price: 550, usage: "Endometriosis treatment", req: true },
  { name: "Cabergoline 0.5", salt: "Cabergoline", category: "Hormone", manufacturer: "Sun Pharma", price: 320, usage: "Prolactin inhibitor", req: true },
  { name: "Humog 75", salt: "HMG", category: "Hormone", manufacturer: "Bharat Serums", price: 1100, usage: "Infertility injection", req: true },

  // 16. Cardiac
  { name: "Atorva 10", salt: "Atorvastatin", category: "Cardiac", manufacturer: "Zydus", price: 60, usage: "Cholesterol management", req: true },
  { name: "Lipitor 10", salt: "Atorvastatin", category: "Cardiac", manufacturer: "Pfizer", price: 80, usage: "Premium cholesterol control", req: true },
  { name: "Rosuvas 10", salt: "Rosuvastatin", category: "Cardiac", manufacturer: "Sun Pharma", price: 150, usage: "Advanced statin for heart", req: true },
  { name: "Ecosprin 75", salt: "Aspirin", category: "Cardiac", manufacturer: "USV", price: 5, usage: "Blood thinner for heart", req: true },
  { name: "Clopilet 75", salt: "Clopidogrel", category: "Cardiac", manufacturer: "Sun Pharma", price: 120, usage: "Prevents heart attack", req: true },
  { name: "Concor 2.5", salt: "Bisoprolol", category: "Cardiac", manufacturer: "Merck", price: 90, usage: "Heart rate regulator", req: true },
  { name: "Digoxin 0.25", salt: "Digoxin", category: "Cardiac", manufacturer: "GSK", price: 25, usage: "Heart failure treatment", req: true },
  { name: "Isosorbide 10", salt: "Isosorbide Mononitrate", category: "Cardiac", manufacturer: "Abbott", price: 40, usage: "Chest pain (Angina) relief", req: true },
  { name: "Sorvitrate 5", salt: "Isosorbide Dinitrate", category: "Cardiac", manufacturer: "Abbott", price: 15, usage: "Emergency chest pain pill", req: true },
  { name: "Amiodarone 200", salt: "Amiodarone", category: "Cardiac", manufacturer: "Sanofi", price: 180, usage: "Heart rhythm control", req: true },
  { name: "MetXL 25", salt: "Metoprolol", category: "Cardiac", manufacturer: "Ajanta", price: 70, usage: "Beta blocker for heart", req: true },
  { name: "Cardace 5", salt: "Ramipril", category: "Cardiac", manufacturer: "Sanofi", price: 160, usage: "Heart protection after attack", req: true },
  { name: "Crestor 10", salt: "Rosuvastatin", category: "Cardiac", manufacturer: "AstraZeneca", price: 450, usage: "High efficacy statin", req: true },
  { name: "Brilinta 90", salt: "Ticagrelor", category: "Cardiac", manufacturer: "AstraZeneca", price: 980, usage: "Post-stent blood thinner", req: true },
  { name: "Ivabrad 5", salt: "Ivabradine", category: "Cardiac", manufacturer: "Lupin", price: 210, usage: "Heart rate lowering drug", req: true },

  // 17. Vitamin Supplement
  { name: "Becosules Z", salt: "B-Complex + Zinc", category: "Vitamin Supplement", manufacturer: "Pfizer", price: 45, usage: "Daily multivitamin", req: false },
  { name: "Limcee 500", salt: "Vitamin C", category: "Vitamin Supplement", manufacturer: "Abbott", price: 25, usage: "Immunity booster", req: false },
  { name: "Shelcal 500", salt: "Calcium & Vit D3", category: "Vitamin Supplement", manufacturer: "Torrent", price: 110, usage: "Bone health", req: false },
  { name: "Neurobion Forte", salt: "Vitamin B12", category: "Vitamin Supplement", manufacturer: "P&G", price: 35, usage: "Nerve health vitamin", req: false },
  { name: "Evion 400", salt: "Vitamin E", category: "Vitamin Supplement", manufacturer: "P&G", price: 40, usage: "Skin and hair vitamin", req: false },
  { name: "Uprise D3 60K", salt: "Vitamin D3", category: "Vitamin Supplement", manufacturer: "Alkem", price: 55, usage: "Weekly D3 supplement", req: false },
  { name: "Revital H", salt: "Multivitamin & Ginseng", category: "Vitamin Supplement", manufacturer: "Sun Pharma", price: 350, usage: "Energy and vitality", req: false },
  { name: "Zincovit", salt: "Multivitamin & Minerals", category: "Vitamin Supplement", manufacturer: "Apex", price: 120, usage: "Recovery multivitamin", req: false },
  { name: "Supradyn", salt: "Multivitamin", category: "Vitamin Supplement", manufacturer: "Bayer", price: 55, usage: "Classic daily vitamin", req: false },
  { name: "A to Z NS", salt: "Multivitamin", category: "Vitamin Supplement", manufacturer: "Alkem", price: 130, usage: "Standard wellness supplement", req: false },
  { name: "Ostocalcium B12", salt: "Calcium", category: "Vitamin Supplement", manufacturer: "GSK", price: 180, usage: "Calcium for all ages", req: false },
  { name: "Autrin", salt: "Iron & B12", category: "Vitamin Supplement", manufacturer: "Pfizer", price: 160, usage: "Anemia treatment", req: false },
  { name: "Dexorange Syrup", salt: "Iron & Folic Acid", category: "Vitamin Supplement", manufacturer: "Franco-Indian", price: 155, usage: "Blood building tonic", req: false },
  { name: "Seven Seas Cod Liver Oil", salt: "Omega 3", category: "Vitamin Supplement", manufacturer: "P&G", price: 280, usage: "Immunity and joint health", req: false },
  { name: "Perfectil", salt: "Multivitamin", category: "Vitamin Supplement", manufacturer: "Meyer Vitabiotics", price: 450, usage: "Skin hair nail support", req: false },

  // 18. Skin Care
  { name: "Betadine Ointment", salt: "Povidone Iodine", category: "Skin Care", manufacturer: "Win-Medicare", price: 110, usage: "Wound antiseptic", req: false },
  { name: "Fourderm", salt: "Chlorhexidine & Steroid", category: "Skin Care", manufacturer: "Cipla", price: 95, usage: "Skin infection treatment", req: true },
  { name: "Panderm ++", salt: "Clobetasol", category: "Skin Care", manufacturer: "Macleods", price: 105, usage: "Severe skin rash relief", req: true },
  { name: "Itaspor 100", salt: "Itraconazole", category: "Skin Care", manufacturer: "Intas", price: 210, usage: "Fungal infection treatment", req: true },
  { name: "Candid Dusting Powder", salt: "Clotrimazole", category: "Skin Care", manufacturer: "Glenmark", price: 150, usage: "Antifungal powder", req: false },
  { name: "T-Bact", salt: "Mupirocin", category: "Skin Care", manufacturer: "GSK", price: 250, usage: "Bacterial skin cream", req: true },
  { name: "Clindamycin Gel", salt: "Clindamycin", category: "Skin Care", manufacturer: "Menarini", price: 180, usage: "Acne treatment gel", req: true },
  { name: "Vicco Turmeric", salt: "Ayurvedic", category: "Skin Care", manufacturer: "Vicco", price: 120, usage: "Natural skin healer", req: false },
  { name: "Soframycin", salt: "Framycetin", category: "Skin Care", manufacturer: "Sanofi", price: 55, usage: "Wound healing cream", req: false },
  { name: "Dermicool", salt: "Menthol", category: "Skin Care", manufacturer: "Emami", price: 90, usage: "Prickly heat relief", req: false },
  { name: "Moiz Cream", salt: "Moisturizer", category: "Skin Care", manufacturer: "Glowderma", price: 320, usage: "Medical grade hydration", req: false },
  { name: "Lulifin Cream", salt: "Luliconazole", category: "Skin Care", manufacturer: "Sun Pharma", price: 280, usage: "Fast antifungal cream", req: true },
  { name: "Skinlite Cream", salt: "Hydroquinone", category: "Skin Care", manufacturer: "Zydus", price: 250, usage: "Hyperpigmentation relief", req: true },
  { name: "Boroline", salt: "Antiseptic Cream", category: "Skin Care", manufacturer: "G.D. Pharma", price: 45, usage: "Classic skin protector", req: false },
  { name: "Melaglow", salt: "Skin Whitening", category: "Skin Care", manufacturer: "Abbott", price: 420, usage: "Glow and spot removal", req: false },

  // 19. Eye Drops
  { name: "Ciplox Eye Drop", salt: "Ciprofloxacin", category: "Eye Drops", manufacturer: "Cipla", price: 20, usage: "Eye infection treatment", req: true },
  { name: "Refresh Tears", salt: "Carboxymethylcellulose", category: "Eye Drops", manufacturer: "Allergan", price: 180, usage: "Dry eye relief", req: false },
  { name: "Itone", salt: "Ayurvedic", category: "Eye Drops", manufacturer: "Dey's", price: 65, usage: "Herbal eye coolant", req: false },
  { name: "Moxif Eye Drop", salt: "Moxifloxacin", category: "Eye Drops", manufacturer: "Sun Pharma", price: 110, usage: "Strong eye antibiotic", req: true },
  { name: "Patanjali Drishti", salt: "Ayurvedic", category: "Eye Drops", manufacturer: "Patanjali", price: 30, usage: "Ayurvedic eye cleanser", req: false },
  { name: "Vigamox", salt: "Moxifloxacin", category: "Eye Drops", manufacturer: "Alcon", price: 350, usage: "Premium eye antibiotic", req: true },
  { name: "Systane Ultra", salt: "Lubricant", category: "Eye Drops", manufacturer: "Alcon", price: 550, usage: "Advanced dry eye therapy", req: false },
  { name: "Tobrex", salt: "Tobramycin", category: "Eye Drops", manufacturer: "Alcon", price: 280, usage: "Pediatric eye antibiotic", req: true },
  { name: "Lotemax", salt: "Loteprednol", category: "Eye Drops", manufacturer: "Bausch & Lomb", price: 420, usage: "Eye steroid for allergy", req: true },
  { name: "Olopat Eye Drop", salt: "Olopatadine", category: "Eye Drops", manufacturer: "Ajanta", price: 140, usage: "Itchy eye allergy relief", req: true },
  { name: "Clearine", salt: "Naphazoline", category: "Eye Drops", manufacturer: "Ipsa", price: 45, usage: "Red eye remover", req: false },
  { name: "Homide", salt: "Homatropine", category: "Eye Drops", manufacturer: "Warren", price: 90, usage: "Eye dilation drops", req: true },
  { name: "Xalatan", salt: "Latanoprost", category: "Eye Drops", manufacturer: "Pfizer", price: 850, usage: "Glaucoma pressure relief", req: true },
  { name: "Combigan", salt: "Brimonidine & Timolol", category: "Eye Drops", manufacturer: "Allergan", price: 920, usage: "Advanced glaucoma control", req: true },
  { name: "Milflox", salt: "Moxifloxacin", category: "Eye Drops", manufacturer: "Sun Pharma", price: 120, usage: "Surgical eye protection", req: true },

  // 20. ENT
  { name: "Otrivin Nasal", salt: "Xylometazoline", category: "ENT", manufacturer: "GSK", price: 95, usage: "Blocked nose relief", req: false },
  { name: "Nasivion", salt: "Oxymetazoline", category: "ENT", manufacturer: "P&G", price: 85, usage: "Quick nasal decongestant", req: false },
  { name: "Waxsolve", salt: "Paradichlorobenzene", category: "ENT", manufacturer: "Mankind", price: 65, usage: "Ear wax softener", req: false },
  { name: "Soliwax", salt: "Ear wax cleaner", category: "ENT", manufacturer: "Zydus", price: 70, usage: "Ear cleaning drops", req: false },
  { name: "Clearwax", salt: "Ear drops", category: "ENT", manufacturer: "Cipla", price: 75, usage: "Painless ear wax removal", req: false },
  { name: "Sinarest", salt: "CPM & Paracetamol", category: "ENT", manufacturer: "Centaur", price: 55, usage: "Cold and sinus relief", req: false },
  { name: "Flixonase", salt: "Fluticasone", category: "ENT", manufacturer: "GSK", price: 420, usage: "Nasal steroid for allergy", req: true },
  { name: "Metaspray", salt: "Mometasone", category: "ENT", manufacturer: "Cipla", price: 450, usage: "Allergic rhinitis spray", req: true },
  { name: "Otogesic Ear Drop", salt: "Lidocaine", category: "ENT", manufacturer: "Warren", price: 60, usage: "Ear pain numbing", req: true },
  { name: "Candibiotic Ear", salt: "Chloramphenicol & Clotrimazole", category: "ENT", manufacturer: "Glenmark", price: 110, usage: "Fungal ear infection", req: true },
  { name: "Otek AC", salt: "Acetic Acid", category: "ENT", manufacturer: "Sun Pharma", price: 95, usage: "Swimmer's ear treatment", req: true },
  { name: "Neosprin Nasal", salt: "Normal Saline", category: "ENT", manufacturer: "Cipla", price: 45, usage: "Natural nasal moisturizer", req: false },
  { name: "Vicks Inhaler", salt: "Menthol & Camphor", category: "ENT", manufacturer: "P&G", price: 60, usage: "Pocket nasal relief", req: false },
  { name: "Septilin", salt: "Herbal", category: "ENT", manufacturer: "Himalaya", price: 150, usage: "Ear and throat immunity", req: false },
  { name: "Kanthil", salt: "Ayurvedic", category: "ENT", manufacturer: "Kanthil", price: 15, usage: "Throat irritation pill", req: false },

  // 21. Pediatric
  { name: "Calpol Suspension", salt: "Paracetamol", category: "Pediatric", manufacturer: "GSK", price: 45, usage: "Children fever relief", req: false },
  { name: "Crocin Drop", salt: "Paracetamol", category: "Pediatric", manufacturer: "GSK", price: 35, usage: "Infant pain and fever", req: false },
  { name: "Colicaid Drop", salt: "Simethicone & Dill Oil", category: "Pediatric", manufacturer: "Meyer", price: 85, usage: "Infant gas and colic", req: false },
  { name: "Augmentin Duo", salt: "Amoxicillin & Clavulanate", category: "Pediatric", manufacturer: "GSK", price: 120, usage: "Child bacterial infection", req: true },
  { name: "Taxim-O Drop", salt: "Cefixime", category: "Pediatric", manufacturer: "Alkem", price: 75, usage: "Strong antibiotic for kids", req: true },
  { name: "Moxikind Drop", salt: "Amoxicillin", category: "Pediatric", manufacturer: "Mankind", price: 60, usage: "Throat infection for kids", req: true },
  { name: "Zincovit Syrup", salt: "Multivitamin", category: "Pediatric", manufacturer: "Apex", price: 110, usage: "Growth and immunity kids", req: false },
  { name: "Zifi 50 Rediuse", salt: "Cefixime", category: "Pediatric", manufacturer: "FDC", price: 95, usage: "Easy child antibiotic", req: true },
  { name: "Emsam Syrup", salt: "Ondansetron", category: "Pediatric", manufacturer: "Emcure", price: 55, usage: "Stops child vomiting", req: true },
  { name: "Enterogermina", salt: "Probiotic", category: "Pediatric", manufacturer: "Sanofi", price: 60, usage: "Child diarrhea recovery", req: false },
  { name: "Pediasure", salt: "Nutritional", category: "Pediatric", manufacturer: "Abbott", price: 650, usage: "Complete child nutrition", req: false },
  { name: "Ostocalcium Syrup", salt: "Calcium", category: "Pediatric", manufacturer: "GSK", price: 160, usage: "Bone growth for kids", req: false },
  { name: "Vizylac Dry Syrup", salt: "Probiotic", category: "Pediatric", manufacturer: "Unichem", price: 80, usage: "Healthy gut for kids", req: false },
  { name: "Ascoril Plus Pediatric", salt: "Ambroxol", category: "Pediatric", manufacturer: "Glenmark", price: 90, usage: "Child cough relief", req: false },
  { name: "Vidaylin Syrup", salt: "Multivitamin", category: "Pediatric", manufacturer: "Abbott", price: 130, usage: "Classic kids multivitamin", req: false },

  // 22. Emergency Medicine
  { name: "Epinephrine Inj", salt: "Adrenaline", category: "Emergency Medicine", manufacturer: "Neon", price: 120, usage: "Severe allergic shock", req: true },
  { name: "Atropine Inj", salt: "Atropine", category: "Emergency Medicine", manufacturer: "Neon", price: 35, usage: "Heart rate booster", req: true },
  { name: "Hydrocortisone Inj", salt: "Steroid", category: "Emergency Medicine", manufacturer: "Abbott", price: 50, usage: "Life saving steroid", req: true },
  { name: "Nitroglycerin Tab", salt: "NTG", category: "Emergency Medicine", manufacturer: "Sun Pharma", price: 15, usage: "Emergency heart pain", req: true },
  { name: "Dopamine Inj", salt: "Dopamine", category: "Emergency Medicine", manufacturer: "Neon", price: 180, usage: "Low blood pressure shock", req: true },
  { name: "Furosemide Inj", salt: "Diuretic", category: "Emergency Medicine", manufacturer: "Sanofi", price: 25, usage: "Fluid in lungs relief", req: true },
  { name: "Diazepam Inj", salt: "Sedative", category: "Emergency Medicine", manufacturer: "Abbott", price: 40, usage: "Continuous seizure stop", req: true },
  { name: "Naloxone Inj", salt: "Antidote", category: "Emergency Medicine", manufacturer: "Neon", price: 450, usage: "Opioid overdose reversal", req: true },
  { name: "Amiodarone Inj", salt: "Cardiac", category: "Emergency Medicine", manufacturer: "Sanofi", price: 250, usage: "Dangerous heart rhythms", req: true },
  { name: "Magnesium Sulfate", salt: "Mineral", category: "Emergency Medicine", manufacturer: "Neon", price: 30, usage: "Pregnancy seizure stop", req: true },
  { name: "Adenosine Inj", salt: "Cardiac", category: "Emergency Medicine", manufacturer: "Neon", price: 650, usage: "Rapid heart beat reset", req: true },
  { name: "Lignocaine Inj", salt: "Anesthetic", category: "Emergency Medicine", manufacturer: "Neon", price: 45, usage: "Heart rhythm stabilizer", req: true },
  { name: "Tranexa Inj", salt: "Tranexamic Acid", category: "Emergency Medicine", manufacturer: "Macleods", price: 120, usage: "Stops internal bleeding", req: true },
  { name: "Dextrose 25%", salt: "Sugar", category: "Emergency Medicine", manufacturer: "Claris", price: 40, usage: "Severe low sugar fix", req: true },
  { name: "Calcium Gluconate", salt: "Calcium", category: "Emergency Medicine", manufacturer: "Neon", price: 55, usage: "Heart safety in toxicity", req: true },

  // 23. Gastrointestinal
  { name: "Loperamide 2", salt: "Loperamide", category: "Gastrointestinal", manufacturer: "Cipla", price: 25, usage: "Stops loose motion", req: false },
  { name: "Eldoper 2", salt: "Loperamide", category: "Gastrointestinal", manufacturer: "Micro Labs", price: 28, usage: "Fast diarrhea relief", req: false },
  { name: "ORS Sachet", salt: "Electrolytes", category: "Gastrointestinal", manufacturer: "FDC", price: 20, usage: "Dehydration recovery", req: false },
  { name: "Cyclopam", salt: "Dicyclomine", category: "Gastrointestinal", manufacturer: "Indoco", price: 45, usage: "Stomach cramp relief", req: false },
  { name: "Meftal Spas", salt: "Mefenamic Acid", category: "Gastrointestinal", manufacturer: "Blue Cross", price: 50, usage: "Abdominal pain relief", req: false },
  { name: "Domstal 10", salt: "Domperidone", category: "Gastrointestinal", manufacturer: "Torrent", price: 35, usage: "Vomiting and nausea", req: false },
  { name: "Perinorm 10", salt: "Metoclopramide", category: "Gastrointestinal", manufacturer: "Ipsa", price: 15, usage: "Stops persistent vomiting", req: true },
  { name: "Emset 4", salt: "Ondansetron", category: "Gastrointestinal", manufacturer: "Cipla", price: 55, usage: "Chemo nausea relief", req: true },
  { name: "Ganaton 50", salt: "Itopride", category: "Gastrointestinal", manufacturer: "Abbott", price: 180, usage: "Digestive movement aid", req: true },
  { name: "Librax", salt: "Chlordiazepoxide & Clidinium", category: "Gastrointestinal", manufacturer: "Abbott", price: 160, usage: "Irritable bowel syndrome", req: true },
  { name: "Colospa 135", salt: "Mebeverine", category: "Gastrointestinal", manufacturer: "Abbott", price: 240, usage: "IBS abdominal pain", req: true },
  { name: "Mesacol 400", salt: "Mesalamine", category: "Gastrointestinal", manufacturer: "Sun Pharma", price: 320, usage: "Ulcerative colitis", req: true },
  { name: "Vibact DS", salt: "Probiotic", category: "Gastrointestinal", manufacturer: "USV", price: 150, usage: "Restores gut flora", req: false },
  { name: "Vizylac", salt: "Probiotic", category: "Gastrointestinal", manufacturer: "Unichem", price: 120, usage: "Antibiotic side effect fix", req: false },
  { name: "Isogel", salt: "Psyllium", category: "Gastrointestinal", manufacturer: "Sun Pharma", price: 200, usage: "Bowel regularity", req: false },

  // 24. Neurology
  { name: "Donecept 5", salt: "Donepezil", category: "Neurology", manufacturer: "Cipla", price: 280, usage: "Alzheimer's memory aid", req: true },
  { name: "Memantee 10", salt: "Memantine", category: "Neurology", manufacturer: "Sun Pharma", price: 350, usage: "Dementia management", req: true },
  { name: "Sizodon 2", salt: "Risperidone", category: "Neurology", manufacturer: "Sun Pharma", price: 90, usage: "Behavioral control", req: true },
  { name: "Syndopa Plus", salt: "Levodopa & Carbidopa", category: "Neurology", manufacturer: "Sun Pharma", price: 180, usage: "Parkinson's tremors", req: true },
  { name: "Pacitane 2", salt: "Trihexyphenidyl", category: "Neurology", manufacturer: "Wyeth", price: 45, usage: "Stiffness and tremors", req: true },
  { name: "Nervijen Plus", salt: "Methylcobalamin", category: "Neurology", manufacturer: "Jenburkt", price: 320, usage: "Nerve regeneration", req: false },
  { name: "Stemetil 5", salt: "Prochlorperazine", category: "Neurology", manufacturer: "Abbott", price: 30, usage: "Dizziness and vertigo", req: true },
  { name: "Vertin 16", salt: "Betahistine", category: "Neurology", manufacturer: "Abbott", price: 160, usage: "Spinning sensation relief", req: true },
  { name: "Migranil", salt: "Ergotamine", category: "Neurology", manufacturer: "Inga", price: 85, usage: "Acute migraine relief", req: true },
  { name: "Sibrium 10", salt: "Flunarizine", category: "Neurology", manufacturer: "Micro Labs", price: 110, usage: "Migraine prevention", req: true },
  { name: "Inderal 10", salt: "Propranolol", category: "Neurology", manufacturer: "Abbott", price: 40, usage: "Anxiety and migraine", req: true },
  { name: "Modalert 100", salt: "Modafinil", category: "Neurology", manufacturer: "Sun Pharma", price: 220, usage: "Excessive sleepiness", req: true },
  { name: "Rizact 10", salt: "Rizatriptan", category: "Neurology", manufacturer: "Cipla", price: 190, usage: "Severe migraine attack", req: true },
  { name: "Napra D 500", salt: "Naproxen & Domperidone", category: "Neurology", manufacturer: "Sun Pharma", price: 130, usage: "Migraine with vomiting", req: true },
  { name: "Aricep 5", salt: "Donepezil", category: "Neurology", manufacturer: "Eisai", price: 420, usage: "Memory loss therapy", req: true },

  // 25. Psychiatry
  { name: "Nexito 10", salt: "Escitalopram", category: "Psychiatry", manufacturer: "Sun Pharma", price: 110, usage: "Depression and anxiety", req: true },
  { name: "Etilaam 0.5", salt: "Etizolam", category: "Psychiatry", manufacturer: "Intas", price: 85, usage: "Short term anxiety relief", req: true },
  { name: "Alprax 0.25", salt: "Alprazolam", category: "Psychiatry", manufacturer: "Torrent", price: 35, usage: "Panic attack relief", req: true },
  { name: "Zolpidem 10", salt: "Zolpidem", category: "Psychiatry", manufacturer: "Sun Pharma", price: 95, usage: "Sleep onset aid", req: true },
  { name: "Sertraline 50", salt: "Sertraline", category: "Psychiatry", manufacturer: "Lupin", price: 140, usage: "OCD and depression", req: true },
  { name: "Fluoxetine 20", salt: "Fluoxetine", category: "Psychiatry", manufacturer: "Cipla", price: 50, usage: "Bulimia and depression", req: true },
  { name: "Olanzapine 5", salt: "Olanzapine", category: "Psychiatry", manufacturer: "Ranbaxy", price: 80, usage: "Schizophrenia control", req: true },
  { name: "Quetiapine 50", salt: "Quetiapine", category: "Psychiatry", manufacturer: "Sun Pharma", price: 150, usage: "Bipolar disorder therapy", req: true },
  { name: "Lithosun 300", salt: "Lithium", category: "Psychiatry", manufacturer: "Sun Pharma", price: 65, usage: "Mania mood stabilizer", req: true },
  { name: "Amitone 10", salt: "Amitriptyline", category: "Psychiatry", manufacturer: "Abbott", price: 25, usage: "Sleep and chronic pain", req: true },
  { name: "Meloset 3", salt: "Melatonin", category: "Psychiatry", manufacturer: "Aristo", price: 75, usage: "Jet lag and sleep cycle", req: false },
  { name: "Petril 0.5", salt: "Clonazepam", category: "Psychiatry", manufacturer: "Micro Labs", price: 60, usage: "Anxiety and seizures", req: true },
  { name: "Zapiz 0.25", salt: "Clonazepam", category: "Psychiatry", manufacturer: "Intas", price: 30, usage: "Daily anxiety control", req: true },
  { name: "Lonazep 0.5", salt: "Clonazepam", category: "Psychiatry", manufacturer: "Sun Pharma", price: 55, usage: "Long acting anxiety relief", req: true },
  { name: "Ativan 1mg", salt: "Lorazepam", category: "Psychiatry", manufacturer: "Pfizer", price: 45, usage: "Pre-surgery sedation", req: true },

  // 26. Orthopedic
  { name: "Shelcal XT", salt: "Calcium & Vitamin D3", category: "Orthopedic", manufacturer: "Torrent", price: 250, usage: "Advanced bone strength", req: false },
  { name: "Jointace DN", salt: "Glucosamine & Diacerein", category: "Orthopedic", manufacturer: "Meyer", price: 480, usage: "Knee osteoarthritis", req: false },
  { name: "Saaz 500", salt: "Sulfasalazine", category: "Orthopedic", manufacturer: "Ipsa", price: 180, usage: "Rheumatoid arthritis", req: true },
  { name: "Folitrax 7.5", salt: "Methotrexate", category: "Orthopedic", manufacturer: "Ipsa", price: 90, usage: "Weekly arthritis drug", req: true },
  { name: "Hycibex", salt: "Multivitamin", category: "Orthopedic", manufacturer: "USV", price: 130, usage: "Orthopedic recovery vitamin", req: false },
  { name: "Bon DK", salt: "Vitamin D3", category: "Orthopedic", manufacturer: "Alkem", price: 50, usage: "Bone mineralization", req: false },
  { name: "Osteofos 70", salt: "Alendronate", category: "Orthopedic", manufacturer: "Cipla", price: 220, usage: "Once weekly osteoporosis", req: true },
  { name: "Terifrac", salt: "Teriparatide", category: "Orthopedic", manufacturer: "Intas", price: 8500, usage: "Bone building injection", req: true },
  { name: "Zobone 4", salt: "Zoledronic Acid", category: "Orthopedic", manufacturer: "Sun Pharma", price: 4200, usage: "Intravenous bone therapy", req: true },
  { name: "D-Rise 60K", salt: "Vitamin D3", category: "Orthopedic", manufacturer: "USV", price: 60, usage: "Strong D3 dose", req: false },
  { name: "Calcimax 500", salt: "Calcium", category: "Orthopedic", manufacturer: "Meyer", price: 140, usage: "Daily calcium support", req: false },
  { name: "Gemcal", salt: "Calcitriol", category: "Orthopedic", manufacturer: "Alkem", price: 210, usage: "Active Vitamin D", req: true },
  { name: "Nurokind Gold", salt: "Multivitamin", category: "Orthopedic", manufacturer: "Mankind", price: 190, usage: "Joint and nerve health", req: false },
  { name: "Mobiswift D", salt: "Diacerein", category: "Orthopedic", manufacturer: "Sun Pharma", price: 320, usage: "Cartilage protector", req: true },
  { name: "Hifenac-P", salt: "Aceclofenac & Paracetamol", category: "Orthopedic", manufacturer: "Intas", price: 55, usage: "Post-surgery pain relief", req: true },

  // 27. Oncology
  { name: "Taxotere", salt: "Docetaxel", category: "Oncology", manufacturer: "Sanofi", price: 15000, usage: "Breast cancer chemo", req: true },
  { name: "Herceptin", salt: "Trastuzumab", category: "Oncology", manufacturer: "Roche", price: 65000, usage: "Targeted cancer therapy", req: true },
  { name: "Nolvadex 20", salt: "Tamoxifen", category: "Oncology", manufacturer: "AstraZeneca", price: 280, usage: "Hormonal breast cancer", req: true },
  { name: "Femara 2.5", salt: "Letrozole", category: "Oncology", manufacturer: "Novartis", price: 850, usage: "Advanced cancer therapy", req: true },
  { name: "Imatinib 400", salt: "Imatinib", category: "Oncology", manufacturer: "Cipla", price: 4500, usage: "Leukemia targeted drug", req: true },
  { name: "Geftinat 250", salt: "Gefitinib", category: "Oncology", manufacturer: "Natco", price: 3200, usage: "Lung cancer treatment", req: true },
  { name: "Xeloda 500", salt: "Capecitabine", category: "Oncology", manufacturer: "Roche", price: 6800, usage: "Oral chemotherapy", req: true },
  { name: "Veenat 400", salt: "Imatinib", category: "Oncology", manufacturer: "Natco", price: 2100, usage: "Blood cancer control", req: true },
  { name: "Erlocip 150", salt: "Erlotinib", category: "Oncology", manufacturer: "Cipla", price: 5500, usage: "Pancreatic cancer therapy", req: true },
  { name: "Sorafenat 200", salt: "Sorafenib", category: "Oncology", manufacturer: "Natco", price: 8800, usage: "Liver cancer drug", req: true },
  { name: "Sutent 12.5", salt: "Sunitinib", category: "Oncology", manufacturer: "Pfizer", price: 12000, usage: "Kidney cancer treatment", req: true },
  { name: "Velcade", salt: "Bortezomib", category: "Oncology", manufacturer: "Janssen", price: 25000, usage: "Myeloma chemo", req: true },
  { name: "Revlimid 10", salt: "Lenalidomide", category: "Oncology", manufacturer: "Celgene", price: 18000, usage: "Multiple myeloma drug", req: true },
  { name: "Keytruda", salt: "Pembrolizumab", category: "Oncology", manufacturer: "MSD", price: 245000, usage: "Immunotherapy for cancer", req: true },
  { name: "Avastin", salt: "Bevacizumab", category: "Oncology", manufacturer: "Roche", price: 48000, usage: "Colorectal cancer chemo", req: true },

  // 28. Gynecology
  { name: "Meftal PD", salt: "Mefenamic Acid", category: "Gynecology", manufacturer: "Blue Cross", price: 35, usage: "Child or mild period pain", req: false },
  { name: "Cyleste", salt: "Ethinylestradiol", category: "Gynecology", manufacturer: "Janssen", price: 420, usage: "Modern contraception", req: true },
  { name: "Gynae CVP", salt: "Citrus Bioflavonoid", category: "Gynecology", manufacturer: "USV", price: 180, usage: "Heavy bleeding control", req: false },
  { name: "Primolut N 5", salt: "Norethisterone", category: "Gynecology", manufacturer: "Bayer", price: 95, usage: "Delaying periods", req: true },
  { name: "Deviry 10", salt: "Medroxyprogesterone", category: "Gynecology", manufacturer: "Torrent", price: 80, usage: "Hormonal bleeding fix", req: true },
  { name: "Normoz", salt: "Myo-Inositol", category: "Gynecology", manufacturer: "Sun Pharma", price: 550, usage: "PCOS management", req: false },
  { name: "Metital", salt: "Myo-Inositol", category: "Gynecology", manufacturer: "Intas", price: 520, usage: "Polycystic ovary support", req: false },
  { name: "Folic Acid 5mg", salt: "Folic Acid", category: "Gynecology", manufacturer: "Emcure", price: 20, usage: "Pregnancy essential vitamin", req: false },
  { name: "Orofer XT", salt: "Ferrous Ascorbate", category: "Gynecology", manufacturer: "Emcure", price: 185, usage: "Pregnancy iron supplement", req: false },
  { name: "Dydroboon 10", salt: "Dydrogesterone", category: "Gynecology", manufacturer: "Mankind", price: 620, usage: "Pregnancy maintenance", req: true },
  { name: "Gestofit 200", salt: "Progesterone", category: "Gynecology", manufacturer: "Sun Pharma", price: 410, usage: "Supporting pregnancy", req: true },
  { name: "MTP Kit", salt: "Mifepristone & Misoprostol", category: "Gynecology", manufacturer: "Cipla", price: 550, usage: "Early pregnancy termination", req: true },
  { name: "Clearblue", salt: "HCG Test", category: "Gynecology", manufacturer: "P&G", price: 350, usage: "Digital pregnancy test", req: false },
  { name: "Pregakem", salt: "HCG Test", category: "Gynecology", manufacturer: "Alkem", price: 65, usage: "Standard pregnancy kit", req: false },
  { name: "Clofert 50", salt: "Clomifene", category: "Gynecology", manufacturer: "Maneesh", price: 140, usage: "Ovulation inducer", req: true },

  // 29. Dental
  { name: "Sensodyne Rapid", salt: "Strontium Acetate", category: "Dental", manufacturer: "GSK", price: 210, usage: "Tooth sensitivity relief", req: false },
  { name: "Thermoseal Gel", salt: "Potassium Nitrate", category: "Dental", manufacturer: "ICPA", price: 120, usage: "Sensitivity management", req: false },
  { name: "Hexidine Mouthwash", salt: "Chlorhexidine", category: "Dental", manufacturer: "ICPA", price: 110, usage: "Gum infection mouthwash", req: false },
  { name: "Listerine Cool Mint", salt: "Essential Oils", category: "Dental", manufacturer: "J&J", price: 180, usage: "Antibacterial mouthwash", req: false },
  { name: "Metrogyl DG Gel", salt: "Metronidazole & Chlorhexidine", category: "Dental", manufacturer: "J.B. Chemicals", price: 85, usage: "Gum inflammation gel", req: false },
  { name: "Kaltat Tab", salt: "Ketorolac", category: "Dental", manufacturer: "Dr. Reddy's", price: 80, usage: "Dental painkiller", req: true },
  { name: "Stolin R", salt: "Strontium Chloride", category: "Dental", manufacturer: "Dr. Reddy's", price: 130, usage: "Gum protection paste", req: false },
  { name: "Clohex ADS", salt: "Chlorhexidine", category: "Dental", manufacturer: "Group Pharma", price: 150, usage: "Anti-stain mouthwash", req: false },
  { name: "Dologel", salt: "Choline Salicylate", category: "Dental", manufacturer: "Dr. Reddy's", price: 75, usage: "Mouth ulcer relief", req: false },
  { name: "Zytee Gel", salt: "Choline Salicylate", category: "Dental", manufacturer: "Raptakos", price: 80, usage: "Quick mouth sore relief", req: false },
  { name: "Orasore Gel", salt: "Lidocaine", category: "Dental", manufacturer: "Wings Pharma", price: 70, usage: "Numbing mouth ulcer gel", req: false },
  { name: "Vicco Vajradanti", salt: "Ayurvedic", category: "Dental", manufacturer: "Vicco", price: 95, usage: "Ayurvedic tooth powder", req: false },
  { name: "Messer Mouthwash", salt: "Povidone Iodine", category: "Dental", manufacturer: "Sun Pharma", price: 140, usage: "Oral antiseptic gargle", req: false },
  { name: "Hiora Forte", salt: "Herbal", category: "Dental", manufacturer: "Himalaya", price: 110, usage: "Natural sensitivity paste", req: false },
  { name: "Dant Kanti", salt: "Ayurvedic", category: "Dental", manufacturer: "Patanjali", price: 85, usage: "Herbal dental care", req: false },

  // 30. Fever & Cold
  { name: "Vicks Action 500", salt: "Paracetamol & CPM", category: "Fever & Cold", manufacturer: "P&G", price: 45, usage: "Multi-symptom cold relief", req: false },
  { name: "Solvin Cold", salt: "Paracetamol & Phenylephrine", category: "Fever & Cold", manufacturer: "Ipsa", price: 50, usage: "Fever with stuffy nose", req: false },
  { name: "Sinarest New", salt: "Paracetamol & CPM", category: "Fever & Cold", manufacturer: "Centaur", price: 55, usage: "Complete cold treatment", req: false },
  { name: "Cheston Cold", salt: "Cetirizine & Phenylephrine", category: "Fever & Cold", manufacturer: "Cipla", price: 48, usage: "Cold and allergy relief", req: false },
  { name: "Maxtra Syrup", salt: "Phenylephrine & CPM", category: "Fever & Cold", manufacturer: "Zydus", price: 95, usage: "Child cold and congestion", req: false },
  { name: "D-Cold Total", salt: "Paracetamol", category: "Fever & Cold", manufacturer: "Reckitt", price: 35, usage: "Quick cold recovery", req: false },
  { name: "Wikoryl", salt: "Paracetamol & CPM", category: "Fever & Cold", manufacturer: "Alembic", price: 52, usage: "Standard cold tablet", req: false },
  { name: "Cebosh", salt: "Paracetamol", category: "Fever & Cold", manufacturer: "Sun Pharma", price: 40, usage: "Fever and aches", req: false },
  { name: "Coldmine", salt: "Paracetamol", category: "Fever & Cold", manufacturer: "Lupin", price: 42, usage: "General cold relief", req: false },
  { name: "Febrex Plus", salt: "Paracetamol", category: "Fever & Cold", manufacturer: "Indoco", price: 58, usage: "Fever and runny nose", req: false },
  { name: "P-500", salt: "Paracetamol", category: "Fever & Cold", manufacturer: "Apex", price: 15, usage: "Classic fever relief", req: false },
  { name: "Kofol", salt: "Herbal", category: "Fever & Cold", manufacturer: "Charak", price: 65, usage: "Ayurvedic cold syrup", req: false },
  { name: "Vicks VapoRub", salt: "Menthol & Camphor", category: "Fever & Cold", manufacturer: "P&G", price: 90, usage: "Congestion relief rub", req: false },
  { name: "Amrutanjan", salt: "Ayurvedic", category: "Fever & Cold", manufacturer: "Amrutanjan", price: 55, usage: "Cold and headache balm", req: false },
  { name: "Zandu Balm", salt: "Ayurvedic", category: "Fever & Cold", manufacturer: "Emami", price: 45, usage: "Quick cold relief balm", req: false },
];

async function expand() {
  try {
    console.log("Upgrading database schema...");
    await pool.query("ALTER TABLE medicines ADD COLUMN IF NOT EXISTS usage TEXT");
    await pool.query("ALTER TABLE medicines ADD COLUMN IF NOT EXISTS manufacturer TEXT");

    console.log("Cleaning existing medicine data...");
    await pool.query("DELETE FROM stock");
    await pool.query("DELETE FROM medicines");

    console.log(`Inserting ${MEDICINES.length} medicines...`);
    const insertedMeds = [];
    for (const med of MEDICINES) {
      const res = await pool.query(
        "INSERT INTO medicines (name, salt, category, price, description, requires_prescription, manufacturer) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id",
        [med.name, med.salt, med.category, med.price, med.usage, med.req, med.manufacturer]
      );
      insertedMeds.push(res.rows[0].id);
    }

    console.log("Populating pharmacy inventory...");
    const pharms = await pool.query("SELECT id FROM pharmacies");
    for (const p of pharms.rows) {
      console.log(`Seeding stock for pharmacy ${p.id}...`);
      for (const mId of insertedMeds) {
        // Each pharmacy gets about 80% of the total medicines in stock
        if (Math.random() > 0.2) {
          await pool.query(
            "INSERT INTO stock (pharmacy_id, medicine_id, quantity) VALUES ($1, $2, $3)",
            [p.id, mId, Math.floor(Math.random() * 150) + 20]
          );
        }
      }
    }

    console.log("✅ Database expanded successfully with 450+ medicine entries!");
    process.exit(0);
  } catch (err) {
    console.error("❌ Expansion failed:", err);
    process.exit(1);
  }
}

expand();
